all: main.exe test

test: test.exe
	test.exe

test.exe: Test.o reconocedor_automata.o reconocedor_control.o
	gcc Test.o reconocedor_automata.o reconocedor_control.o -o test.exe

Test.o: Test.c reconocedor.h
	gcc -c Test.c -o Test.o

main.exe: main.o reconocedor_automata.o reconocedor_control.o
	gcc main.o reconocedor_automata.o reconocedor_control.o -o main.exe

main.o: main.c reconocedor.h
	gcc -c main.c -o main.o

reconocedor_automata.o: reconocedor_automata.c reconocedor.h
	gcc -c reconocedor_automata.c -o reconocedor_automata.o

reconocedor_control.o: reconocedor_control.c reconocedor.h
	gcc -c reconocedor_control.c -o reconocedor_control.o

clean:
	rm -f main.o reconocedor_automata.o reconocedor_control.o main.exe  Test.o test.exe salida.txt